linters:
  # https://golangci-lint.run/usage/linters/
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - importas
    - inamedparam
    - interfacebloat
    - lll
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  gci:
    sections:
      - standard
      - prefix(git.limango.tech)
      - prefix(github.com)
      - prefix(golang.org)
      - default
    custom-order: true

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

  godot:
    exclude:
      - "^ @"

  varnamelen:
    ignore-names:
      - err
      - id
      - k
      - i
      - v