version: "3"
services:
  go:
    image: golang:1.22.2-alpine
    restart: no
    entrypoint: /usr/src/app/entrypoint.sh
    working_dir: /usr/src/app
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./:/usr/src/app